### ISSUE TITLE
Request new action to copy files to application web directory

### ISSUE THREAD

**Issue by wayne-chung** [icatproject/icat.utils#2]
For topcatv2, I want to be able to add configuration files (.json) to the application's web directory
i.e. 
```
$GLASSFISH_HOME/glassfish/domains/domain1/applications/$APPLICATION_NAME/
```
Looking at setup_utils.py, I can pass an optional dir parameter to copy the file but it's quite difficult to work out the glassfish domain and $APPLICATION_NAME.

Could an action be added to setup_utils.py to copy files to the application web directory? I would like to be able to specify a relative path to where I want to save the file. e.g.
```
action.installWebFile("topcat.json", "config")
```
Saves the file to: 
```
$GLASSFISH_HOME/glassfish/domains/domain1/applications/topcatv2-0.1-SNAPSHOT/config/topcat.json
```

**Comment by fisherab** [comment]
This has already been fixed
